sudo: true
dist: xenial

language: python

cache:
    directories:
        - $HOME/.cache/pip

matrix:
    include:
        # Install Check
        - python: 3.6
          env: INSTALL_CHECK=YES
          stage: Tests
        # Security
        - python: 3.7
          env: TOXENV=bandit
          stage: Static Checks
        # Linting
        - python: 3.7
          env: TOXENV=lint
          stage: Static Checks
        # MyPy
        - python: 3.7
          env: TOXENV=mypy
          stage: Static Checks

install: pip install tox
script:
    - |
      if [[ -n INSTALL_CHECK ]];
        then .travis/install-check.sh;
        else tox -- -vv;
      fi;
