# https://packaging.python.org/guides/supporting-windows-using-appveyor/

environment:

    matrix:
        # The only tests we perform on Windows are actual code tests.
        # All linting, static analysis, etc are only run on Linux.
        # Python 3.6
        - PYTHON: "C:\\Python36"
          TOXENV: "py36-local"
        - PYTHON: "C:\\Python36-x64"
          TOXENV: "py36-local"
        - PYTHON: "C:\\Python36"
          TOXENV: "py36-integ"
        - PYTHON: "C:\\Python36-x64"
          TOXENV: "py36-integ"
        - PYTHON: "C:\\Python36"
          TOXENV: "py36-examples"
        - PYTHON: "C:\\Python36-x64"
          TOXENV: "py36-examples"
        # Python 3.7
        - PYTHON: "C:\\Python37"
          TOXENV: "py37-local"
        - PYTHON: "C:\\Python37-x64"
          TOXENV: "py37-local"
        - PYTHON: "C:\\Python37"
          TOXENV: "py37-integ"
        - PYTHON: "C:\\Python37-x64"
          TOXENV: "py37-integ"
        - PYTHON: "C:\\Python37"
          TOXENV: "py37-examples"
        - PYTHON: "C:\\Python37-x64"
          TOXENV: "py37-examples"

install:
    # Prepend newly installed Python to the PATH of this build
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    # Check the Python version to verify that the correct version was installed
    - "python --version"
    - "python -m pip install --upgrade setuptools wheel tox"

build: off

test_script:
    - "tox -- -vv"
