name: Local Tests

on: [pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - run: |
          python -m pip install --upgrade pip
          pip install --upgrade tox
      - name: run test
        run: |
          tox -e build
          python test/test_pipx-in-pipx.py --dist-directory "$(pwd)/dist"
